/*Final Project - Computer Science
This program will be the Caesar coder which will code/translate the
plaintext message using the caesar cipher.
*/

import java.util.ArrayList;
public class VigenereCoder{
   ArrayList<String> alphabet = new ArrayList<String>();
   //Here is the Coder method which will take the plaintext and translate it into Caesar 
   public char[] Coder(String word, String codeword){
      int count = 0;
      char[] codeword2 = new char[word.length()];
      char[] coded = new char[word.length()];
      alphabet.add(0,"a");
      alphabet.add(1,"b");
      alphabet.add(2,"c");
      alphabet.add(3,"d");
      alphabet.add(4,"e");
      alphabet.add(5,"f");
      alphabet.add(6,"g");
      alphabet.add(7,"h");
      alphabet.add(8,"i");
      alphabet.add(9,"j");
      alphabet.add(10,"k");
      alphabet.add(11,"l");
      alphabet.add(12,"m");
      alphabet.add(13,"n");
      alphabet.add(14,"o");
      alphabet.add(15,"p");
      alphabet.add(16,"q");
      alphabet.add(17,"r");
      alphabet.add(18,"s");
      alphabet.add(19,"t");
      alphabet.add(20,"u");
      alphabet.add(21,"v");
      alphabet.add(22,"w");
      alphabet.add(23,"x");
      alphabet.add(24,"y");
      alphabet.add(25,"z");
      word = word.toLowerCase();
      for (int j = 0; j == word.length(); j++){
         codeword2[j]=codeword.charAt(count);
         count++;
         if (count == codeword.length()){
            count = 0;
         }
      }
      for (int i = 0; i == word.length(); i++){
         if (((codeword.charAt(i) == 'a') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'z'))){
            coded[i]='a';
         }
         else if (((codeword.charAt(i) == 'b') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'z'))){
            coded[i]='b';
         }
         else if (((codeword.charAt(i) == 'c') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'z'))){
            coded[i]='c';
         }
         else if (((codeword.charAt(i) == 'd') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'z'))){
            coded[i]='d';
         }
         else if (((codeword.charAt(i) == 'e') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'z'))){
            coded[i]='e';
         }
         else if (((codeword.charAt(i) == 'f') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'z'))){
            coded[i]='f';
         }
         else if (((codeword.charAt(i) == 'g') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'z'))){
            coded[i]='g';
         }
         else if (((codeword.charAt(i) == 'h') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'z'))){
            coded[i]='h';
         }
         else if (((codeword.charAt(i) == 'i') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'z'))){
            coded[i]='i';
         }
         else if (((codeword.charAt(i) == 'j') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'z'))){
            coded[i]='j';
         }
         else if (((codeword.charAt(i) == 'k') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'z'))){
            coded[i]='k';
         }
         else if (((codeword.charAt(i) == 'l') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'z'))){
            coded[i]='l';
         }
         else if (((codeword.charAt(i) == 'm') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'z'))){
            coded[i]='m';
         }
         else if (((codeword.charAt(i) == 'n') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'z'))){
            coded[i]='n';
         }
         else if (((codeword.charAt(i) == 'o') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'z'))){
            coded[i]='o';
         }
         else if (((codeword.charAt(i) == 'p') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'z'))){
            coded[i]='p';
         }
         else if (((codeword.charAt(i) == 'q') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'z'))){
            coded[i]='q';
         }
         else if (((codeword.charAt(i) == 'r') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'z'))){
            coded[i]='r';
         }
         else if (((codeword.charAt(i) == 's') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'z'))){
            coded[i]='s';
         }
         else if (((codeword.charAt(i) == 't') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'z'))){
            coded[i]='t';
         }
         else if (((codeword.charAt(i) == 'u') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'z'))){
            coded[i]='u';
         }
         else if (((codeword.charAt(i) == 'v') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'z'))){
            coded[i]='v';
         }
         else if (((codeword.charAt(i) == 'w') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'z'))){
            coded[i]='w';
         }
         else if (((codeword.charAt(i) == 'x') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'd')) || ((codeword.charAt(i) == 't') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'i')) || ((codeword.charAt(i) == 'o') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'n')) || ((codeword.charAt(i) == 'j') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'g') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 's')) || ((codeword.charAt(i) == 'e') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'a') && (word.charAt(i) == 'x')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'y')) || ((codeword.charAt(i) == 'y') && (word.charAt(i) == 'z'))){
            coded[i]='x';
         }
         else if (((codeword.charAt(i) == 'a') && (word.charAt(i) == 'z')) || ((codeword.charAt(i) == 'z') && (word.charAt(i) == 'a')) || ((codeword.charAt(i) == 'y') && 
         (word.charAt(i) == 'b')) || ((codeword.charAt(i) == 'x') && (word.charAt(i) == 'c')) || ((codeword.charAt(i) == 'w') && (word.charAt(i) == 'd')) || 
         ((codeword.charAt(i) == 'v') && (word.charAt(i) == 'e')) || ((codeword.charAt(i) == 'u') && (word.charAt(i) == 'f')) || ((codeword.charAt(i) == 't') && 
         (word.charAt(i) == 'g')) || ((codeword.charAt(i) == 's') && (word.charAt(i) == 'h')) || ((codeword.charAt(i) == 'r') && (word.charAt(i) == 'i')) || 
         ((codeword.charAt(i) == 'q') && (word.charAt(i) == 'j')) || ((codeword.charAt(i) == 'p') && (word.charAt(i) == 'k')) || ((codeword.charAt(i) == 'o') && 
         (word.charAt(i) == 'l')) || ((codeword.charAt(i) == 'n') && (word.charAt(i) == 'm')) || ((codeword.charAt(i) == 'm') && (word.charAt(i) == 'n')) || 
         ((codeword.charAt(i) == 'l') && (word.charAt(i) == 'o')) || ((codeword.charAt(i) == 'k') && (word.charAt(i) == 'p')) || ((codeword.charAt(i) == 'j') && 
         (word.charAt(i) == 'q')) || ((codeword.charAt(i) == 'i') && (word.charAt(i) == 'r')) || ((codeword.charAt(i) == 'h') && (word.charAt(i) == 's')) || 
         ((codeword.charAt(i) == 'g') && (word.charAt(i) == 't')) || ((codeword.charAt(i) == 'f') && (word.charAt(i) == 'u')) || ((codeword.charAt(i) == 'e') && 
         (word.charAt(i) == 'v')) || ((codeword.charAt(i) == 'd') && (word.charAt(i) == 'w')) || ((codeword.charAt(i) == 'c') && (word.charAt(i) == 'x')) || 
         ((codeword.charAt(i) == 'b') && (word.charAt(i) == 'y'))){
            coded[i]='z';
         }
         else{
            coded[i]='y';
         }
         
      }
   return coded;
   }
}